services:
  # --- SONARR -------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF}/sonarr:/config
      - ${DATA}:/data
    ports:
      - 8989:8989

  # --- RADARR -------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF}/radarr:/config
      - ${DATA}:/data
    ports:
      - 7878:7878

  # --- PROWLARR -----------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.25
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF}/prowlarr:/config
    ports:
      - 9696:9696

  # --- rdtclient ------------------------------------------------
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    mem_limit: 768m
    cpus: 0.5
    volumes:
      - ${CONF}/rdtclient:/data/db
      - ${DATA}/downloads:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF}/bazarr:/config
      - ${DATA}:/data
    mem_limit: 384m
    cpus: 0.25
    ports:
      - 6767:6767
    restart: unless-stopped


  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    mem_limit: 128m
    cpus: 0.1
    volumes:
      - ${CONF}/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped


  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    mem_limit: 512m
    cpus: 0.5
    volumes:
      - ${CONF}/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped


  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    mem_limit: 256m
    cpus: 0.25
    volumes:
      - ${CONF}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    mem_limit: 64m
    cpus: 0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    mem_limit: 256m
    cpus: 0.25
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    mem_limit: 128m
    cpus: 0.1
    ports:
      - 9000:9000
    volumes:
      - ${CONF}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
